# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ff605cdd1f0757ce78748f85138ffab6aae4cef2fab5ec0a9b2fe47aa50f172ea9d4a6e4054cb1a2a813a6585419310a369e424643c81dbd9903546987a4db4

test:
  secret_key_base: b12012573adb06fb6fc45016f9d5915df55c2614a83918b16e568424de9f4b8914bc415fc8e3bb60365dc5c1c60d99f45dcd6a331e8d6046edc292f266906523

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
